write_snapshot_print <- function(object, fn = NULL) {

    # temp file
    if (is.null(fn)) {
        fn <- tempfile()
        sink(fn)
        print(object)
        sink()
        return(fn)
    }

    # persistent file
    if (!file.exists) {
        # only write when we are "at home" (via test runner)
        if (tinytest::at_home()) {
            msg <- sprintf('Snapshot not found: %s. Snapshots can be generated by running the `tinytest` suite "at home" using one of the test runners: `run_test_dir()` or `run_test_file()`. See `?tinytest::at_home`', fn)
        }
    }


    } else {
        dir.create(dirname(fn), showWarnings = FALSE, recursive = TRUE)
    }


    msg <- sprintf("Snapshot not found.\nGenerating new snapshot: %s", fn)
    return(msg)
}


read_snapshot_print <- function(fn) {
    out <- readChar(fn, file.info(fn)$size)
    return(out)
}