write_snapshot_print <- function(object, fn = NULL) {
        browser()
    if (is.null(fn)) {
        fn <- file.path(tempdir(), fn)
    } else {
        if (!file.exists)

    }
        if (tinytest::at_home()) {
            fn <- file.path("_tinyviztest", paste0(tempfile(), ".txt"))
        } else {
            msg <- sprintf('Snapshot not found: %s. Snapshots can be generated by running the `tinytest` suite "at home" using one of the test runners: `run_test_dir()` or `run_test_file()`. See `?tinytest::at_home`', fn)
            return(msg)
        }

    } else {
        dir.create(dirname(fn), showWarnings = FALSE, recursive = TRUE)
    }

    sink(fn)
    print(object)
    sink()

    msg <- sprintf("Snapshot not found.\nGenerating new snapshot: %s", fn)
    return(msg)
}

read_snapshot_print <- function(fn) {
    out <- readChar(fn, file.info(fn)$size)
    return(out)
}