write_snapshot_print <- function(object, fn = NULL) {

    # temp file
    if (is.null(fn)) {
        fn <- tempfile()
        sink(fn)
        print(object)
        sink()
        return(fn)
    }

    # persistent file: only write in test runners like tinytest::run_test-dir()`
    if (tinytest::at_home()) {
        msg <- sprintf("Generating new snapshot:\n%s", fn)
        dir.create(dirname(fn), showWarnings = FALSE, recursive = TRUE)
        sink(fn)
        print(object)
        sink()
        return(msg)

    } else {
        msg <- sprintf('Snapshot not found: %s. Snapshots can be generated by running the `tinytest` suite "at home" using one of the test runners: `run_test_dir()` or `run_test_file()`. See `?tinytest::at_home`', fn)
        return(msg)
    }
}


read_snapshot_print <- function(fn) {
    out <- readChar(fn, file.info(fn)$size)
    return(out)
}