portable_label <- function(label, warn = TRUE) {
    regex <- "[^[:alnum:]|_|-]"
    out <- gsub(regex, "_", label)
    if (isTRUE(warn) && grepl(regex, label)) {
        msg <- 'The `label` must be a "portable" string with only alpha-numeric characters, hyphens, or underscores. Other characters were replaced by underscores:
        %s 
        %s'
        msg <- sprintf(msg, label, out)
        warning(msg, call. = TRUE)
    }
    return(out)
}


generate_snapshot_at_home <- function(fn) {
    if (tinytest::at_home()) {
        msg <- sprintf("Generating new snapshot: %s", fn)
        warning(msg, call. = FALSE)
    } else {
        msg <- sprintf('Snapshot not found: %s. Snapshots can be generated by running the `tinytest` suite "at home" using one of the test runners: `run_test_dir()` or `run_test_file()`. See `?tinytest::at_home`', fn)
        stop(msg, call. = FALSE)
    }
}