snapshot_label <- function(label, extension = NULL, warn = TRUE) {
    regex <- "[^[:alnum:]|_|-]"
    out <- gsub(regex, "_", label)
    if (isTRUE(warn) && grepl(regex, label)) {
        msg <- 'The `label` must be a "portable" string with only alpha-numeric characters, hyphens, or underscores. Other characters were replaced by underscores:
        %s 
        %s'
        msg <- sprintf(msg, label, out)
        warning(msg, call. = TRUE)
    }

    if (!is.null(extension)) {
        out <- paste0(out, ".", extension)
    }

    return(out)
}


generate_snapshot_at_home <- function(fn) {
    if (!tinytest::at_home()) {
        msg <- sprintf('Snapshot not found: %s. Snapshots can be generated by running the `tinytest` suite "at home" using one of the test runners: `run_test_dir()` or `run_test_file()`. See `?tinytest::at_home`', fn)
        stop(msg, call. = FALSE)
    } else {
        msg <- sprintf("Generating new snapshot: %s", fn)
        return(msg)
    }
}


snapshot_file <- function(fn, extension = "txt") {
    # test runners give us certainty
    if (tinytest::at_home()) {
        path <- file.path("_tinyviztest", fn)

    # source() can be in any working directory. Try common ones.
    } else {
        path <- file.path("inst/tinytest/_tinyviztest", fn)
        if (!file.exists(path)) {
            path <- file.path("_tinyviztest", fn)
        }
    }

    if (!is.null(extension)) {
        path <- paste0(path, ".", extension)
    }

    return(path)
}